# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateTimeField(blank=True, default='2000-01-01')),
                ('isMale', models.BooleanField(default='False')),
                ('pesel', models.DecimalField(blank=True, decimal_places=0, default='999', max_digits=19, unique=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, default='999', max_digits=11, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('isAccepted', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.DoctorProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.PatientProfile')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
