# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, default='999', max_digits=11),
        ),
    ]
